name: uonly_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: 12.1.3
  image_picker:
  flutter_html:
  font_awesome_flutter: ^10.8.0
  carousel_slider: 5.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.9
  url_launcher:
  connectivity_plus:
  dio: 5.4.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  webview_flutter: 4.4.4
  file_picker:
  lottie: ^3.0.0
  curved_navigation_bar: ^1.0.3
  share_plus:
  path_provider:
  syncfusion_flutter_charts: 24.2.7
  intl:
  flutter_svg: ^2.0.10+1
  flutter_animate:
  syncfusion_flutter_xlsio:
  device_info_plus: 9.1.2
  package_info_plus: ^8.0.0
  in_app_update: ^4.2.2
  flutter_otp_text_field: ^1.1.3+2
  hidden_drawer_menu: ^3.0.1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  animated_text_kit:
  youtube_player_flutter:
  crypto: ^3.0.5
  flutter_pdfview: ^1.4.0
  excel: ^2.0.5
  flutter_inappwebview: ^6.1.5
  printing: ^5.10.4
  pdf: ^3.10.1
  collection: ^1.17.2
  flutter_downloader:
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  open_file: ^3.5.10
  custom_refresh_indicator: ^4.0.1
  random_string: ^2.3.1
  permission_handler: ^12.0.0+1
  pinput: ^3.0.1
  flutter_contacts: ^1.1.9+2
#  geolocator: ^14.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.1
  material_design_icons_flutter: ^7.0.7296
  mobile_scanner: ^6.0.10







dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
   - assets/
  #   - images/a_dot_ham.jpeg


